version: "3.9"
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: hires_test

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./resources:/app/resources


  adminer:
    image: adminer
    ports:
      - 8081:8080
